//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Mangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public byte[] DoctorPicture { get; set; }
        public decimal DoctorCharge { get; set; }
        public Nullable<int> CategoryId { get; set; }
    }
}
